// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYiylAjJnR72IE_vUIrEZcjl1e_HBikI',
    appId: '1:341398935670:web:59b3f9d9f56f95723ba757',
    messagingSenderId: '341398935670',
    projectId: 'medconnect-e81ba',
    authDomain: 'medconnect-e81ba.firebaseapp.com',
    storageBucket: 'medconnect-e81ba.firebasestorage.app',
    measurementId: 'G-5WJ8G0PKWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPD-jAyZJVrgw5vQzc1u1-8QatuMHXoRU',
    appId: '1:341398935670:android:cfd99ea3900bc1113ba757',
    messagingSenderId: '341398935670',
    projectId: 'medconnect-e81ba',
    storageBucket: 'medconnect-e81ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2qNcq03hHTQ67Xv_z_YyYiMC8DULsoOk',
    appId: '1:341398935670:ios:6729499cf24578a63ba757',
    messagingSenderId: '341398935670',
    projectId: 'medconnect-e81ba',
    storageBucket: 'medconnect-e81ba.firebasestorage.app',
    iosBundleId: 'com.example.occasion',
  );
}
