// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // `databaseURL` (Realtime Database, région europe-west1 — voir
  // presence_service.dart) : requis explicitement par le package
  // `firebase_database`, qui ne le devine pas automatiquement pour une
  // base régionale (uniquement pour l'ancien format us-central1).
  static const String _databaseURL =
      'https://occasion-10cdb-default-rtdb.europe-west1.firebasedatabase.app';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZ-F8Tpl77yZUxkRkXOr-HnGrfr6OcbM',
    appId: '1:101610899328:web:94ef5e76085b599b486365',
    messagingSenderId: '101610899328',
    projectId: 'occasion-10cdb',
    authDomain: 'occasion-10cdb.firebaseapp.com',
    databaseURL: _databaseURL,
    storageBucket: 'occasion-10cdb.firebasestorage.app',
    measurementId: 'G-C7WDKKRSMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARE6huabcDtrZOMGLcxj86NlNyZeyqeOM',
    appId: '1:101610899328:android:8145ca9b4fbab568486365',
    messagingSenderId: '101610899328',
    projectId: 'occasion-10cdb',
    databaseURL: _databaseURL,
    storageBucket: 'occasion-10cdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrBeSsmzA15KykFuAk17fJQJP0qMPSkKE',
    appId: '1:101610899328:ios:1ef95a310386d06c486365',
    messagingSenderId: '101610899328',
    projectId: 'occasion-10cdb',
    databaseURL: _databaseURL,
    storageBucket: 'occasion-10cdb.firebasestorage.app',
    iosBundleId: 'com.example.occasion',
  );
}
